Adding tests and support for Django 4.2 - 5x and removing EOL versions of python and django
jazzband/django-newsletter pull request #394
Opened 2024-12-10 16:27 UTC by sebastian-muthwill

Update python and django versions
- dropped tests for Python <3.7
- dropped tests for Django <4.2
- added tests for Python 3.11, 3.12, 3.13
- added tests for Django >=4.2

as discussed in https://github.com/jazzband/django-newsletter/issues/392

2024-12-11 13:38 UTC, sebastian-muthwill commented
Created an issue to get the changes released: https://github.com/jazzband/help/issues/383

2024-12-11 17:57 UTC, newearthmartin requested changes
Let's not leave Django versions out unless we have a good reason.
Let's keep LooseVersion if possible.

2024-12-11 17:57 UTC, newearthmartin commented on newsletter/models.py
What's wrong with LooseVersion? It's better than manually parsing the version number. Please leave like it was unless there is some good reason.

(Also it's better to just remove code instead of leaving it commented)

2024-12-11 17:57 UTC, newearthmartin commented on tests/test_web.py
Better use a `TEST_PASSWORD` variable if we are going to repeat it all over

2024-12-11 17:57 UTC, newearthmartin commented on CHANGES.rst
Why are we removing support for those Django versions? What's the reason? Is there something incompatible?

2024-12-12 07:59 UTC, sebastian-muthwill commented on newsletter/models.py
TBH this part I was already in the Django-5 branch I based my changes on and I did not checked that. 
From what I see this is a patch in order to support Django versions <1.9. 
It would depend here on the general decision if such old versions need to be supported or not.

2024-12-12 08:09 UTC, sebastian-muthwill commented on CHANGES.rst
This is maybe more of a "philosophical" question. 
I try to follow in all my projects the release cycle of Python and Django and migrate the code base always at least to the latest LTS version. 
In general it becomes more and more challenging to support EOL versions because it requires patches for compatibility purpose and this effects the maintainability (like here: https://github.com/jazzband/django-newsletter/pull/394/files/d5300e560ad14dda0c625290236e00d7b98d86b7#diff-4d097d8e2ddb447f443dc2a92699225f61c2f7370d077988d93c83cc572d71f9)

2024-12-12 08:12 UTC, sebastian-muthwill commented
I just saw that @dokterbob already released v1.0 to PyPi. 
May we have your opinion here as well. I think we should at least merge this PR to master as well to keep master and PyPi version in sync. 
After that we can discuss if older versions should be supported or not.

2024-12-13 20:28 UTC, newearthmartin commented on newsletter/models.py
It's not a good practice to leave commented lines. Please remove them.

And also there is no point in removing `LooseVersion` and then manually parsing the version. You can just revert that.

2024-12-13 20:45 UTC, newearthmartin commented on CHANGES.rst
I'm in favor of dropping support for older versions that require these patches. In that case we need to remove the patches, too. But that will not take us up to 4.2. We can support more versions.

Remember that this is not "your" or "my" project. I also keep my projects always on the latest versions, but this library has been around for many years and there may be many projects using older Django versions. We don't want to force them to upgrade unnecessarily.

2024-12-13 20:49 UTC, newearthmartin commented
Before merging please address the code quality comments I made. Don't leave commented lines and remove the patches for older Django versions.

2025-01-29 09:49 UTC, adRn-s commented
I don't know if I have a strict positioning on the matter, but I'd like to say that a new version of this package that drops support for, say, Django 1.9 is not necessarily wrong. Anyone running Django 1.9 could still use the old django-newsletter version that supports that. This is perfectly normal, expected, and I'd argue even desired (if it makes it easier on manteinance and new developments.)

2025-01-30 01:30 UTC, newearthmartin commented
> if it makes it easier on manteinance and new developments.

My suggestion is to drop old versions when they conflict with development. Not before just because. When a new feature requires a higher version of Django, then support can be dropped.

2025-08-14 16:34 UTC, newearthmartin commented
Hi @sebastian-muthwill it seems I forgot about this PR and went and duplicated your efforts on another PR to fix the automated build and tests https://github.com/jazzband/django-newsletter/pull/399

I now get the need to drop the older versions, but it's not just because they are old but because dependencies don't work, for example sorl-thumbanail needs django >= 4.

I did this because I made another PR https://github.com/jazzband/django-newsletter/pull/397 and tests were broken. 

Apparently no one cares about this anymore? Nobody is reviewing PRs, so what do you think we should do? Has anyone managed to contact @dokterbob ? Does anyone have rights to approve PRs?

2025-08-14 16:41 UTC, merged

2025-08-14 16:41 UTC, newearthmartin commented
I just joined jazzband and merged this PR

2025-08-14 17:56 UTC, newearthmartin commented
Builds are still broken but I fixed them with https://github.com/jazzband/django-newsletter/pull/399
I'll be merging it later today, I'll wait a little bit in case someone wants to review it before I merge it